cache: bundler

language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2.2
  - 2.3.0

sudo: false

bundler_args: --without development --retry=3 --jobs=3

before_install:
  - gem update bundler

env:
  - "RAILS_VERSION=2.3.2"
  - "RAILS_VERSION=3.0.20"
  - "RAILS_VERSION=3.1.12"
  - "RAILS_VERSION=3.2.22.2"
  - "RAILS_VERSION=4.0.13"
  - "RAILS_VERSION=4.1.16"
  - "RAILS_VERSION=4.2.7"
  - "RAILS_VERSION=5.0.0.1"

matrix:
  allow_failures:
    - rvm: 2.0
      env: RAILS_VERSION=2.3.2
    - rvm: 2.0
      env: RAILS_VERSION=5.0.0.1
    - rvm: 2.1
      env: RAILS_VERSION=2.3.2
    - rvm: 2.1
      env: RAILS_VERSION=5.0.0.1
  fast_finish: true
